trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: NuGetToolInstaller@1
 
- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime
    
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      docker --version
      cd WebApplication
      dotnet publish WebApplication.csproj -c Release -o publish
      cp Dockerfile publish

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnection'
    repository: 'budjenvladimir/health_clinic_web_application'
    command: 'buildAndPush'
    Dockerfile: 'publish/Dockerfile'
    buildContext: 'publish'
    tags: |
      $(Build.BuildId)
      latest