trigger:
- develop

pool:
  vmImage: ubuntu-18.04


steps:

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk

- task: Bash@3
  displayName: Build, Test, Publish
  inputs:
    targetType: 'inline'
    script: |
      docker --version
      cd WebApplication
      dotnet publish WebApplication.csproj -c Release -o publish
      cp Dockerfile publish
      

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnection'
    repository: 'budjenvladimir/health_clinic_web_application'
    command: 'buildAndPush'
    Dockerfile: 'publish/Dockerfile'
    buildContext: 'publish'
    tags: |
      $(Build.BuildId)
      latest